controller_list:
  - name: fake_arm0_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_arm1_controller
    joints:
      - R_joint_1
      - R_joint_2
      - R_joint_3
      - R_joint_4
      - R_joint_5
      - R_joint_6
  - name: fake_gripper0_controller
    joints:
      - left_finger_1_joint_0
      - left_finger_2_joint_0
      - right_finger_1_joint_0
      - right_finger_2_joint_0
  - name: fake_gripper1_controller
    joints:
      - left_finger_1_joint_1
      - left_finger_2_joint_1
      - right_finger_1_joint_1
      - right_finger_2_joint_1