# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm0
  joint_model_group_pose: home0
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - left_finger_1_joint_0
    - left_finger_2_joint_0
    - right_finger_1_joint_0
    - right_finger_2_joint_0
    - R_joint_1
    - R_joint_2
    - R_joint_3
    - R_joint_4
    - R_joint_5
    - R_joint_6
    - left_finger_1_joint_1
    - left_finger_2_joint_1
    - right_finger_1_joint_1
    - right_finger_2_joint_1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm0_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: arm1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - R_joint_1
      - R_joint_2
      - R_joint_3
      - R_joint_4
      - R_joint_5
      - R_joint_6
  - name: gripper0_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_finger_1_joint_0
      - left_finger_2_joint_0
      - right_finger_1_joint_0
      - right_finger_2_joint_0
  - name: gripper1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_finger_1_joint_1
      - left_finger_2_joint_1
      - right_finger_1_joint_1
      - right_finger_2_joint_1